### ISSUE TITLE
Moving to JSON

### ISSUE THREAD

**Issue by 07typing** [07typing/starchat#15]
No longer will i be using the terrible format `&&&&&||||||||||&&&&&`, i will use JSON.

This issue will be closed when the task is finished, multiple things will be changed over the next coming time. Please suggest any ideas, before I close this issue.

**Comment by turtle0x1** [comment]
Move your responses to json ? look at using symfonys response object https://api.symfony.com/4.0/Symfony/Component/HttpFoundation/JsonResponse.html

**Comment by 07typing** [comment]
seems nice, but i dont feel like putting the pain upon inserting a new library, is there a native php way to do this? honestly 404's and stuff depend on the server side configuration, and what about 200 requests (OK), i dont think i would need to do those

**Comment by turtle0x1** [comment]
Its only a pain because you are not using composer and proper namespaces, even then its still not a pain its as simple  as 

```
require __DIR__ . "/path/to/vendor/autoload.php";
use Symfony\Component\HttpFoundation\JsonResponse;

// Do some query

$response = new JsonResponse(["array"=>"data"]);
$response->send();
```

**Comment by 07typing** [comment]
version 0.7 released
