### ISSUE TITLE
SQL Injections

### ISSUE THREAD

**Issue by turtle0x1** [07typing/starchat#16]
There sql injetions everywhere seriously please read the php manual and look at the comments https://secure.php.net/manual/en/pdostatement.execute.php

**Comment by 07typing** [comment]
Um... I've been using a function to remove SQL injections, is it broken?

**Comment by turtle0x1** [comment]
I followed the variables, you really should use PDO, checkout https://stackoverflow.com/questions/5741187/sql-injection-that-gets-around-mysql-real-escape-string right at the bottom of the top answer "Otherwise, you're vulnerable even though you're using mysql_real_escape_string()..."

**Comment by 07typing** [comment]
oh dont worry, ive been moving to pdo, itll fix some bugs like when i use a hash in the text

**Comment by 07typing** [comment]
version 0.7 released, no sql injections were in the program, but i moved to pdo, so its more secure
