### ISSUE TITLE
Force DB Name

### ISSUE THREAD

**Issue by emilengler** [07typing/starchat#20]
Hello, starchat forces you to use the dbname "starchat".
This needs to be fixed because a lot of webspace providers don't allow you to choose the database name.
For example you are forced to use dbnames like u123456-starchat.
This needs to be fixed

**Comment by 07typing** [comment]
probably would be a good thing to put in "mysqlinfo.php", so the user can pick a database name

also i need to add custom port support not everyone uses the default mysql port
