### ISSUE TITLE
Classes, Classes & More Classes

### ISSUE THREAD

**Issue by turtle0x1** [07typing/starchat#21]
Another step towards making this repository even worth looking at is using composer & breaking up your functions into classes (with proper namespaces)

**Comment by emilengler** [comment]
I absolutely agree!

**Comment by 07typing** [comment]
Thanks, should i get it into the 0.7.3 release that I am working on?

**Comment by turtle0x1** [comment]
You should aim to get it in as soon as possible, this will likely be a drastic restructure (or lead to) of your project. Once its ready to be merged it you typically bump a major version number, but as no-body (I assume, not to be harsh) is using your library it doesn't matter

**Comment by 07typing** [comment]
Yes, currently no one that I am aware of is self hosting starchat, but me on my server, my server uses the latest of 0.7.3a. Even if people were hosting it, all of the "main" data is stored in MySQL (logins, messages, contacts), so say you had to remove and reinstall starchat, you would only need to fill out the setup MySQL credentials. So even the users won't notice a difference from a

**Comment by turtle0x1** [comment]
Changing the external / internal api requires a major version bump

**Comment by 07typing** [comment]
Good, then it will be 0.8.0

**Comment by turtle0x1** [comment]
I retract my previous comment its late, semantic versioning says you can change anything you like on the 0.X.X branch!

**Comment by 07typing** [comment]
Hi, I am double thinking what you mean, first of all I will switch to composer once we start using dependencies. For now we use no dependencies. Also, for me to go to classes wouldnt help us much, because all php files are programs, not libraries, so we wouldnt do something like new Starchat, but code cleanup at this point would be highly neccessary

**Comment by 07typing** [comment]
I know but classes will not help starchat in any way, nor will they be useful since starchat isnt a library, i may still attempt to use classes though in the future
