### ISSUE TITLE
Phpunit

### ISSUE THREAD

**Issue by turtle0x1** [07typing/starchat#23]
Good job on starting to do tests but please use phpunit a proper testing framework this will probably be made easier by #21

**Comment by 07typing** [comment]
By tests are you referring to my use of CI?

**Comment by turtle0x1** [comment]
Yeah ci is about testing (and deploying, but looking through the ci you are doing testing)

**Comment by turtle0x1** [comment]
Why was this closed without a reason ?

**Comment by nekobit1** [comment]
Sorry, forgot the reason, CI/CD is now just to do a check for errors
